apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: default
spec:
  ports:
  - nodePort: 30123
    port: 5432
    targetPort: 5432
  selector:
    spilo-role: master
  sessionAffinity: None
  type: NodePort