apiVersion: v1
kind: Service
metadata:
  name: backendbuilding-nodeport
  namespace: default
spec:
  ports:
  - nodePort: 30135
    port: 8000
    targetPort: 8000
  selector:
    app: tides-backend
  sessionAffinity: None
  type: NodePort

