apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tides-deployment-back
spec:
  selector:
    matchLabels:
      app: tides-backend
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: tides-backend
    spec:
      containers:
      - name: tides-backend
        image: anniesunqin/cloudtidesmaster_backend:latest
        ports:
        - containerPort: 8000

