apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tides-deployment-front
spec:
  selector:
    matchLabels:
      app: tides-frontend
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: tides-frontend
    spec:
      containers:
      - name: tides-frontend
        image: anniesunqin/cloudtidesmaster_frontend:latest
        ports:
        - containerPort: 3000

