version: "3.8"
services:
  database:
    image: "postgres:alpine"
    restart: always
    env_file:
      - .env
    ports:
      - "4201:5432"
    volumes:
      - server_db:/var/lib/postgresql/data
  backend:
    build: ./tides-server
    volumes:
      - ./tides-server:/data
    env_file:
      - .env
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - database
    entrypoint: ["/build/backend", "--local"]
  frontend:
    build: ./ui
    volumes:
      - ./ui:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

volumes: 
  server_db:
