apiVersion: v1
kind: Service
metadata:
  name: frontendbuilding-nodeport
  namespace: default
spec:
  ports:
  - nodePort: 30233
    port: 3000
    targetPort: 3000
  selector:
    app: tides-frontend
  sessionAffinity: None
  type: NodePort

