apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtides-frontend-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: cloudtides-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudtides-frontend
    spec:
      containers:
        - name: cloudtides-frontend
          image: ericshen97/cloudtides_frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: cloudtides-frontend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: cloudtides-frontend
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30124
