name: frontend-CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the module directory
        uses: actions/checkout@v2

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ericshen97/cloudtides_frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ui
          tags: "latest"

      - name: Transfer yml file to Aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "ui/cloudtides_frontend.yml"
          target: "/root"

      - name: Upgrade the platform using SSH
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/ui
            kubectl delete -f cloudtides_frontend.yml
            kubectl apply -f cloudtides_frontend.yml
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}